# Generated by Django 5.2.3 on 2025-06-13 02:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2025, 6, 13, 2, 49, 2, 567984)),
        ),
        migrations.AddField(
            model_name='todo',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='description',
            field=models.CharField(default='1', max_length=255),
            preserve_default=False,
        ),
    ]
