# Generated by Django 5.2.3 on 2025-06-13 02:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_todo_created_at_todo_deadline_todo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2025, 6, 13, 2, 50, 49, 833903)),
        ),
    ]
